# Generated by Django 5.0 on 2024-01-01 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('code_adh', models.AutoField(primary_key=True, serialize=False)),
                ('nom_adh', models.CharField(max_length=100)),
                ('nbr_emprunts_adh', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('code_auteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_auteur', models.CharField(max_length=100)),
                ('prenom_auteur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('code_livre', models.AutoField(primary_key=True, serialize=False)),
                ('titre_livre', models.CharField(max_length=200)),
                ('nbre_page', models.IntegerField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField()),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.adherent')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.livre')),
            ],
        ),
    ]
